# Generated by Django 3.1.4 on 2020-12-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0002_auto_20201207_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionchoice',
            old_name='option_a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='questionchoice',
            old_name='option_b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='questionchoice',
            old_name='option_c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='questionchoice',
            old_name='option_d',
            new_name='D',
        ),
    ]
