# Generated by Django 3.1.4 on 2020-12-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0003_auto_20201207_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='correct_answer',
            field=models.CharField(choices=[('A', models.CharField(max_length=500)), ('B', models.CharField(max_length=500)), ('C', models.CharField(max_length=500)), ('D', models.CharField(max_length=500))], default=False, max_length=30),
        ),
    ]
