# Generated by Django 3.1.4 on 2020-12-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0004_auto_20201207_0642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
