# Generated by Django 3.1.4 on 2020-12-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0005_delete_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_denotation',
            field=models.CharField(choices=[('min', 'min'), ('hour', 'hour')], default='min', max_length=6),
            preserve_default=False,
        ),
    ]
