# Generated by Django 3.1.4 on 2020-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0006_auto_20201210_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=60)),
                ('score', models.CharField(blank=True, max_length=10)),
                ('course', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
