# Generated by Django 3.1.4 on 2020-12-10 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0007_leadership_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership_board',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 19)),
            preserve_default=False,
        ),
    ]
