# Generated by Django 3.1.4 on 2020-12-11 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0008_leadership_board_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership_board',
            name='last_renewal',
            field=models.DateField(default=datetime.date(2020, 8, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadership_board',
            name='trials',
            field=models.IntegerField(default=0),
        ),
    ]
