# Generated by Django 3.1.4 on 2020-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0009_auto_20201211_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='quiz\\courses\\capture1.PNG', max_length=60, upload_to='category'),
            preserve_default=False,
        ),
    ]
