# Generated by Django 3.1.4 on 2020-12-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0010_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='course',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizTest.quiz'), on_delete=django.db.models.deletion.CASCADE, to='quizTest.courses'),
        ),
    ]
