# Generated by Django 3.1.4 on 2020-12-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0012_auto_20201211_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
    ]
