# Generated by Django 3.1.4 on 2020-12-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizTest', '0013_auto_20201211_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='images',
            field=models.ImageField(default='quiz\\media\\courses\\image.jpg', upload_to='courses/'),
        ),
    ]
